CREATE USER '__USER__'@'%' IDENTIFIED BY '__PASSWORD__';

GRANT
    USAGE
ON *.* TO '__USER__'@'%';

GRANT
    ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT,
    REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, ALTER ROUTINE,
    CREATE ROUTINE, CREATE TEMPORARY TABLES, EXECUTE, LOCK TABLES
ON __TABLE__.* TO '__USER__'@'%';

FLUSH PRIVILEGES;